version: '{build}'
image: Visual Studio 2019

environment:
  MARIA_PWD: Password12!
  PGSQL_PWD: Password12!

services:
  - mysql
  - postgresql

build: off

test_script:
  - dotnet restore
  - dotnet test
